Mutation:
    type: object
    config:
        fields:
            createQuiz:
                type: "Int!"
                resolve: '@=mutation("App\\GraphQL\\Mutation\\QuizMutation::createQuiz", args)'
                args:
                    quiz: "QuizInput!"
            updateQuiz:
                type: "Boolean!"
                resolve: '@=mutation("App\\GraphQL\\Mutation\\QuizMutation::updateQuiz", args)'
                args:
                    id: "Int!"
                    quiz: "UpdateQuizInput!"
            deleteQuiz:
                type: "Boolean!"
                resolve: '@=mutation("App\\GraphQL\\Mutation\\QuizMutation::deleteQuiz", args)'
                args:
                    id: "Int!"
