Query:
    type: object
    config:
        fields:
            quizzes:
                type: "[Quiz]"
                resolve: '@=query("App\\GraphQL\\Resolver\\QuizResolver::resolveQuizzes", args)'
            quiz:
                type: "Quiz"
                args:
                    id:
                        type: "Int!"
                resolve: '@=query("App\\GraphQL\\Resolver\\QuizResolver::resolveQuiz", args)'
            searchQuizzes:
                type: "[Quiz]"
                args:
                    searchParams:
                        type: "SearchQuizInput!"
                resolve: '@=query("App\\GraphQL\\Resolver\\QuizResolver::resolveQuizSearch", args)'
            filterByTags:
                type: "[Quiz]"
                args:
                    tagIds:
                        type: "[Int!]"
                resolve: '@=query("App\\GraphQL\\Resolver\\QuizResolver::resolveFilterByTags", args)'

            attemptsForUser:
                type: "[QuizAttempt]"
                args:
                    id:
                        type: "Int!"
                resolve: '@=query("App\\GraphQL\\Resolver\\QuizAttemptResolver::resolveAttemptsForUser", args)'
            attempt:
                type: "QuizAttempt"
                args:
                    id:
                        type: "Int!"
                resolve: '@=query("App\\GraphQL\\Resolver\\QuizAttemptResolver::resolveAttempt", args)'
