Question:
    type: object
    config:
        fields:
            id: "Int!"
            text: "String!"
            options: "[String]!"
            correctAnswer: "[Int]!"
            type:
                type: "QuestionTypes"
                resolve: "@=value.getType().value"
                description: 'Either "one" or "multiple"'
            position:
                type: "Int!"
                description: 'The index of the question in the quiz''s questions array'
            explanation: "String"
