Question:
    type: object
    config:
        fields:
            id: "Int!"
            text: "String!"
            options: "[String]!"
            correctAnswer: "[Int]!"
            type:
                type: "QuestionTypes"
                resolve: "@=value.getType().value"
            position: "Int!"
            explanation: "String"
