QuizInput:
    type: input-object
    config:
        fields:
            title: "String!"
            description: "String"
            questions: "[QuestionInput]!"
            tags: "[TagInput]"

UpdateQuizInput:
    type: input-object
    config:
        fields:
            title: "String!"
            description: "String"
            questions: "[UpdateQuestionInput]!"
            tags: "[TagInput]"

SearchQuizInput:
    type: input-object
    config:
        fields:
            keywords: "String"
