QuizInput:
    type: input-object
    config:
        fields:
            title: "String!"
            description: "String"
            questions: "[QuestionInput]!"
            tags: "[TagInput]"
            furtherReading: "String"

UpdateQuizInput:
    type: input-object
    config:
        fields:
            title: "String!"
            description: "String"
            questions: "[UpdateQuestionInput]!"
            tags: "[TagInput]"
            furtherReading: "String"

SearchQuizInput:
    type: input-object
    config:
        fields:
            keywords: "String"
