Tag:
    type: object
    config:
        fields:
            id: "Int!"
            name:
                type: "String!"
                description: 'The unique identifier of the tag'
            displayName:
                type: "String!"
                description: 'The formatted name of the tag displayed to the user'
